apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-deployment
  labels:
    app: frontend
spec:
  replicas: 3 
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: site_ui
          image: alibaba.gitlab.com/front-team/site_ui:latest
          ports:
            - containerPort: 5173